=== yzqaq/cecJsonVerify/schema/schema_notification_equip_charge_status_req.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "StartChargeSeq": {
            "type": "string",
            "maxLength": 27,
            "minLength": 27
        },
        "StartChargeSeqStat": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ]
        },
        "ConnectorID": {
            "type": "string"
        },
        "ConnectorStatus": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                255
            ]
        },
        "CurrentA": {
            "type": "number"
        },
        "CurrentB": {
            "type": "number"
        },
        "CurrentC": {
            "type": "number"
        },
        "VoltageA": {
            "type": "number"
        },
        "VoltageB": {
            "type": "number"
        },
        "VoltageC": {
            "type": "number"
        },
        "Soc": {
            "type": "number"
        },
        "PlateNo": {
            "type": "string"
        },
        "Phone": {
            "type": "string"
        },
        "Vin": {
            "type": "string"
        },
        "StartTime": {
            "type": "string"
        },
        "EndTime": {
            "type": "string"
        },
        "TotalPower": {
            "type": "number",
            "title": "%.3",
            "exclusiveMaximum": 1,
            "exclusiveMinimum": 1
        },
        "ElecMoney": {
            "type": "number",
            "title": "%.2",
            "exclusiveMaximum": 1,
            "exclusiveMinimum": 1
        },
        "SeviceMoney": {
            "type": "number",
            "title": "%.2",
            "exclusiveMaximum": 1,
            "exclusiveMinimum": 1
        },
        "TotalMoney": {
            "type": "number",
            "title": "%.2",
            "exclusiveMaximum": 1,
            "exclusiveMinimum": 1
        },
        "SumPeriod": {
            "type": "integer"
        },
        "ChargeDetails": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/charge_detail"
            },
            "minItems":1
        }
    },
    "required": [
        "StartChargeSeq",
        "StartChargeSeqStat",
        "ConnectorID",
        "ConnectorStatus",
        "CurrentA",
        "VoltageA",
        "Soc",
        "StartTime",
        "EndTime",
        "TotalPower",
        "ChargeDetails"
    ],
    "definitions": {
        "charge_detail": {
            "type": "object",
            "properties": {
                "DetailStartTime": {
                    "type": "string"
                },
                "DetailEndTime": {
                    "type": "string"
                },
                "ElecPrice": {
                    "type": "number",
                    "title": "%.4",
                    "exclusiveMaximum": 1,
                    "exclusiveMinimum": 1
                },
                "SevicePrice": {
                    "type": "number",
                    "title": "%.4",
                    "exclusiveMaximum": 1,
                    "exclusiveMinimum": 1
                },
                "DetailPower": {
                    "type": "number",
                    "title": "%.3",
                    "exclusiveMaximum": 1,
                    "exclusiveMinimum": 1
                },
                "DetailElecMoney": {
                    "type": "number",
                    "title": "%.2",
                    "exclusiveMaximum": 1,
                    "exclusiveMinimum": 1
                },
                "DetailSeviceMoney": {
                    "type": "number",
                    "title": "%.2",
                    "exclusiveMaximum": 1,
                    "exclusiveMinimum": 1
                }
            },
            "required": [
                "DetailStartTime",
                "DetailEndTime",
                "ElecPrice",
                "SevicePrice",
                "DetailPower",
                "DetailElecMoney",
                "DetailSeviceMoney"
            ]
        }
    }
}

=== yzqaq/cecJsonVerify/json/query_equip_charge_status_res.json
{
    "StartChargeSeq": "MA01H3BQ1202011101428100001",
    "StartChargeSeqStat": 4,
    "ConnectorID": "20099_1",
    "ConnectorStatus": 3,
    "TotalPower": 0.021,
    "CurrentA": 7,
    "VoltageA": 397,
    "Soc": 30,
    "StartTime": "2020-11-10 14:28:12",
    "EndTime": "2020-11-10 14:29:11",
    "ChargeDetails": [
        {
            "DetailStartTime": "2020-11-10 14:28:12",
            "DetailEndTime": "2020-11-10 14:28:57",
            "ElecPrice": 0.78,
            "SevicePrice": 0.2,
            "DetailPower": 0.021,
            "DetailElecMoney": 0.16,
            "DetailSeviceMoney": 0.04
        }
    ]
}
